# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4  # Updated to v4

#       - name: Setup Node
#         uses: actions/setup-node@v4  # Updated to v4
#         with:
#           node-version: 20  # Ensure this matches your local environment

#       - name: Install dependencies
#         uses: bahmutov/npm-install@v1

#       - name: Build project
#         run: npm run build

#       - name: Upload production-ready build files
#         uses: actions/upload-artifact@v4  # Updated to v4
#         with:
#           name: production-files
#           path: ./dist

#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4  # Ensures latest repo state

#       - name: Download artifact
#         uses: actions/download-artifact@v4  # Updated to v4
#         with:
#           name: production-files
#           path: ./dist

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v4  # Updated to latest version
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist


name: Deploy

on:
  push:
    branches:
      - main

permissions:  # Ensure correct permissions for deployment
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # More stable for Vite
          cache: 'npm'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: NODE_ENV=production npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ""  # Remove if using a custom domain
